groups:
  - name: sts-availability
    rules:
      - alert: ExporterTargetDown
        expr: up{job=~"nginx-master|nginx-uat|cadvisor"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Exporter down ({{ $labels.job }})"
          description: "Exporter target {{ $labels.instance }} in {{ $labels.job }} is not reachable."
